### ISSUE TITLE
Issues with segments and linear devices

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#129]
Remarks:

LinearDev

* LinearDev::new()
It is the users responsibility to ensure no overlap in segments. No order is guaranteed or expected.

* LinearDev::segments()
A slice of Segments is returned in the same order they were added.

* LinearDev::dm_table()
The table is generated in the order in which the segments are given.

* LinearDev::extend()
It is the user's responsibility to ensure no overlap in the union of segments already belonging to the device and new segments to be added.
The method tries to coalesce the last segment currently belonging to the device with the first segment to be added. Coalescing requires that the devices of the two segments be the same. Consequently, this extra step suggests that there is an implicit ordering to the order in which segments are presented to the extend method. This is not necessarily correct.

Big question: Does it matter to devicemapper how the table is constructed? Is there any advantage to _maybe_ coalescing some regions some times as is done in extend() method? We should find out.
Other big question: Is it really a good idea to write LinearDev::new() so that it makes the device only if it is not there? The segments passed as an argument may be very different from the segments the kernel knows about. And even if they are the same, they may be in a very different order. This makes checking hard and time consuming.
Other big question: Is a slice of segments the right thing to return for segments() function? Is there some other arrangement that is more valuable?

ThinPoolDev

extend_data() and extend_meta() just call their corresponding device's extend() method.

StratPool:

* StratPool::setup()
  - calls get_blockdevs()
      + segments are presented to blockdev's range allocator in any order, but that is handled by RangeAlloc::insert_ranges()
      + blockdevs may be returned in any order, therefore blockdevs may be added in any order to BlockDevMgr. Therefore, when new segments are allocated, they may come from any blockdev, not necessarily the last one from which they were allocated.
   - In setup(), the segments are discovered in the order in which they were previously written out, which should correspond to their previous order. This is a precarious invariant to rely on though, and it would be necessary to rely on if the plan were to check the equivalence of tables in LinearDev::new().
   - In extend_data() the blockdevmgr allocates the space from the shuffled blockdevs before passing it to the thin pool. Therefore, the segments could be from anywhere, and need not be contiguous with the previous segments.
   - In initialize(), segments are just allocated from the underlying blockmgr in whatever order the blockmgr sees fit.

ThinPool:

  incomplete

**Comment by agrover** [comment]
> Big question: Does it matter to devicemapper how the table is constructed? Is there any advantage to maybe coalescing some regions some times as is done in extend() method? We should find out.

One implicit assumption (that we could make explicit, I guess) is that the user will not pass in contiguous segments. There's no benefit to multiple table rows when one will do. Both for `extend` and `new`.

The reason that `extend` merges the first new with the last old segment (if possible) is that even with the above assumption, it could end up with contiguous segments if it didn't merge.

> Other big question: Is it really a good idea to write LinearDev::new() so that it makes the device only if it is not there? The segments passed as an argument may be very different from the segments the kernel knows about. And even if they are the same, they may be in a very different order. This makes checking hard and time consuming.

The order of segments must be maintained once a Lineardev has been established. Users of a LinearDev expect something written to sector 10 to always show up at sector 10, after all. If segments are mapped in a different order then the user will see this as corruption, because the offset of each segment within the lineardev is determined by the total lengths of segments before it.

If `extend` is passed multiple segments, it could be that a segment other than the first one is contiguous with the last existing segment, in which case by reordering it to be first, one less table entry would be needed (reordering is safe b/c they're not in use yet). But that's a pretty high-level behavior that might not be appropriate here. I would think the caller's higher-level allocator is where segment reordering or allocation policy should be. The caller should've just passed the contiguous segment first.

**Comment by mulkieran** [comment]
Does devicemapper have anything to say about the order of the entries in the table, other than that it would be nice to merge contiguous segments if possible?

**Comment by agrover** [comment]
Sorry, I don't understand the question.

**Comment by mulkieran** [comment]
This has all been resolved in various PRs.
