### ISSUE TITLE
f.write_all() doesn't seem to be behaving as advertized 

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#260]
We have an assurance that the table we are uploading is the table we specify.

See #255 for some further discussion.

**Comment by trgill** [comment]
I think if we combine linear and flakey and write to the block device, we need to align the segment sizes need to be a multiple of the block size.

If we've got this table setup:
```
# dmsetup table linear-dev
0 20 linear 252:0 0
20 20 flakey 252:0 20 0 1 0 
```

As soon was we write the 17th sector we get an IO error because I think the underlying layer is writing the entire block which crosses into the flakey segment.

**Comment by mulkieran** [comment]
That makes sense...and would explain some of my errors. It's not clear what the best thing to do would be, though. LinearDev's don't really know about data block sizes.

**Comment by agrover** [comment]
This really seems like a bug to me. A single I/O that spans multiple targets should be properly split, and should not require granularity above sector. At least that's my initial expectation...

**Comment by trgill** [comment]
The same setup works if I use fio to run the IO.  For example this script:

```
#!/bin/bash
set -x
DATA_DEV=/dev/vda
DEV_NAME=linear-dev

DATA_SIZE=20

echo -e "0 ${DATA_SIZE} linear ${DATA_DEV} 0\\n${DATA_SIZE} ${DATA_SIZE} flakey 
${DATA_DEV} ${DATA_SIZE} 0 1\\n" | dmsetup create $DEV_NAME

#echo -e "0 ${DATA_SIZE} linear ${DATA_DEV} 0\\n${DATA_SIZE} ${DATA_SIZE} linear
 ${DATA_DEV} ${DATA_SIZE} \\n" | dmsetup create $DEV_NAME

fio ~/sector-write.fio --filename=/dev/mapper/$DEV_NAME

dmsetup table $DEV_NAME
dmsetup remove $DEV_NAME
```
With the following in sector-write.fio - writing exactly 20 sectors (10240 bytes)

```
[sector-write]
rw=write
size=10240
direct=1
name=sequential-write-direct
bs=512
```

If I increase the size to 10241 bytes, I see an IO failure on the flakey segment as expected.

Not sure exactly what the f.write_all() call does.

**Comment by trgill** [comment]
This problem seems to be related to how the Rust f.write_all() is implemented.

The flakey target works as expected when I use fio or dd to write sectors.

If I set the flakey target to 0 downtime (nothing fails) - the tests using write_all work.

Notes:
* The DM test suite uses loopbacks.  I tested with a regular block device and see the same problems with "write_all()".
* The order doesn't matter.  If there is any flakey segment on the DM device - the write_all() fails on the first sector write to the linear segment.

* I tried with a segment size of 4096 - no difference.

**Comment by trgill** [comment]
Additional Notes: 

A program written in C does the same thing unless the O_DIRECT flag is set and the buffer is aligned.  The following works to write a single sector within a block of a failing/flakey sector.

```
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

#define SECTOR_SIZE 512

int main(int argc, char *argv[]) {
        int offset = 0;
        int length = 21;
        int flags = O_RDWR | O_DIRECT;
        int rc;

        char *sector = aligned_alloc(SECTOR_SIZE, SECTOR_SIZE);

        memset(sector, 7, SECTOR_SIZE);
        int fd=open("/dev/mapper/linear-dev", flags);

        lseek(fd, offset, SEEK_SET);
        for (int i = 0; i < length; i++) {
                rc = write(fd, sector, SECTOR_SIZE);
                if (rc < 0)
                        printf("sector write error at offset = %d + %d\n %s", offset, i, strerror(errno));

                if (fsync(fd) != 0)
                        printf("fsync() error\n");
        }

        close(fd);
}
```

**Comment by agrover** [comment]
I think we understand this much better now. Is there still work to be done, or are we satisfied and can possibly close this issue? Thanks.

**Comment by mulkieran** [comment]
I have no objection to closing it.
