### ISSUE TITLE
I'm not certain that the meta_ and data_ devices in a thin pool are certain to be linear devs

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#52]

**Comment by mulkieran** [comment]
I would think that there would be quite a few different kinds of devices that might occupy that role.

**Comment by agrover** [comment]
Agree. There's probably space for some (trait-based?) generalization here at some point.

**Comment by mulkieran** [comment]
The need for trait-based generalization is getting more urgent, see #70 for examples.

**Comment by agrover** [comment]
Could be a fun little project.

**Comment by mulkieran** [comment]
Except for the "fun" and the "little".

**Comment by mulkieran** [comment]
Shared:

* ```name()```
* ```dstr()```
* ```size()```
* ```devnode()```
* ```teardown()```

Is that useful?

**Comment by agrover** [comment]
After further reflection, I think this may be a theoretical library restriction in `ThinPoolDev` but not an issue that Stratis will actually run into. Even in 2.0, Stratis's Flex layer is LinearDevs to handle spanning & extending across multiple lower-level devices if necessary. The LinearDevs will just be on top of RaidDevs and/or IntegrityDevs instead of base blockdevs.

Even ignoring Stratis, the value of a ThinPoolDev on top of something other than a LinearDev may not be great. You could presumably put a ThinPoolDev on top of two RaidDevs, but they each cannot be extended (without inserting a LinearDev! heh) and probably are the wrong size ratio of meta to data device.

**Comment by mulkieran** [comment]
Might as well leave as LinearDev...at least for now. We don't really know how to extend all DmDevices, we might need a subcategory.
